homepage/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.mainScreen, name='main-selection-page'),
    path("addbook/", views.addBook, name='adding-book-page'),
    path('booklist/', views.listBook, name='viewing-book-page'),
    path('booklist/<str:book_id>', views.bookPage, name='viewing-book-spec-page'),
    path('search/', views.search, name='search')
]

siteRoot/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls), 
    path("login/", auth_views.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path("", include('homepage.urls'), name='homepage-redirect-here-pls'),
    path("addbook/", include('homepage.urls')),
    path("booklist/", include('homepage.urls')),
    path("register/", user_views.register, name='register_users'),
]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class books(models.Model):
    title = models.CharField(max_length=100)
    summary = models.TextField()
    author = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    checked_out = models.BooleanField(default=False)
    id = models.CharField(max_length=100, primary_key=True)
    book_owner = models.CharField(max_length=100)
    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

class add_book(forms.Form):
    title = forms.CharField(max_length=100)
    summary = forms.CharField(widget=forms.Textarea)
    author = forms.CharField(max_length=100)
    id = forms.CharField(max_length=100)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            'title',
            'summary',
            'author',
            'id',
            Submit('submit', 'Submit', css_class='btn-success')
        )
class checkinoutBook(forms.Form):
    User = forms.CharField(max_length=100, required=True)
    def __init__(self, text='Check In', *args, **kwargs):
        
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'GET'
        if text != 'Check In':
            self.helper.layout = Layout(
                'User',
                Submit('submit', text, css_class="btn_btn-primary_btn-lg_btn-block")
            )
        else:
            self.helper.layout = Layout(
                Submit('submit', text, css_class="btn_btn-primary_btn-lg_btn-block")
            )

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import books
from .forms import add_book, checkinoutBook
from django.db.models import Q

boxes = []
# {'title':'Number 1'}
#for i in range(30):
#    boxes.append({'title':f'Number {i+4}'})
# Create your views here.
def isPartOfGroup(user, group_name):
    return user.groups.filter(name=group_name).exists()
def mainScreen(request):
    return render(request, "siteRoot/home.html", {'isPartOf':isPartOfGroup(request.user, 'librarian')})

def addBook(request):
    #return render(request, "siteRoot/addBook.html")
    if isPartOfGroup(request.user, 'librarian'):

        if request.method == "POST":
            form = add_book(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                summary = form.cleaned_data['summary']
                author = form.cleaned_data['author']
                id = form.cleaned_data['id']
                if ' ' in id:
                    xyz = list(id)
                    for y, i in enumerate(xyz):
                        if i == ' ':
                            xyz[y] = '_'
                    id = ''.join(xyz)
                books.objects.create(title=title, summary=summary, author=author, id=id)
                print("Book added", title, summary, author, id)
                return render(request, "siteRoot/addBook.html", {'form':add_book(), 'success':True, 'isPartOf':isPartOfGroup(request.user, 'librarian')})
            else:
                return render(request, "siteRoot/addBook.html", {'form':form, 'success':False, 'isPartOf':isPartOfGroup(request.user, 'librarian')})
        form = add_book()
        return render(request, 'siteRoot/addBook.html', {'form': form, 'isPartOf':isPartOfGroup(request.user, 'librarian')})
    return render(request, 'siteRoot/home.html' , {'isPartOf':isPartOfGroup(request.user, 'librarian')})

def listBook(request):
    boxes = []
    box= []
    from .models import books
    ls = books.objects.all()
    for i in ls:
        boxes.append({'title':f'{i.title}', 'id':f'{i.id}', 'author':f'{i.author}', 'summary':f'{i.summary}'})
        box.append(i)
    return render(request, "siteRoot/bookList.html", {"boxes":boxes, 'yes':len(boxes) < 10, 'box':box, 'isPartOf':isPartOfGroup(request.user, 'librarian')})

def bookPage(request, book_id):
    booky = books.objects.get(id=book_id)
    if request.method == "GET":
        print('Getting data and proccessing', request.GET)
        if booky.checked_out:
            text = 'Check In'
        else:
            text='Check Out'
        form = checkinoutBook(text, request.GET)
        print('Data is Valid')
        if form.is_valid():
            if text == 'Check Out':
                text = 'Check In'
                booky.checked_out = True
                booky.book_owner = form['User'].value().strip()
                booky.save()
                form = checkinoutBook(text)
        else:
            text = 'Check Out'
            booky.checked_out = False
            booky.book_owner = "Librarian"
            booky.save()
            form = checkinoutBook(text)

        
        return render(request, 'siteRoot/bookPage.html', {'book_id':booky, 'form':form, 'isPartOf':isPartOfGroup(request.user, 'librarian')})
    if booky.checked_out:
        form = checkinoutBook()
    else:
        form = checkinoutBook('Check Out')
    return render(request, "siteRoot/bookPage.html", {"book_id":booky, 'isPartOf':isPartOfGroup(request.user, 'librarian'), 'form':form})

def search(request):
    query = None
    result = []
    result1 = []
    if request.method == "GET":
        query = request.GET.get("search")
        result = books.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))
        result1 = (books.objects.filter(id__icontains=query))
        result2 = []
        for xy, i in enumerate(result1):
            if i.id == query:
                result2.append(result1[xy])
    return render(request, 'siteRoot/search.html', {'query':query, 'result':result, 'yes':len(result) < 10, 'result1':result2,  'isPartOf':isPartOfGroup(request.user, 'librarian')})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm
# Create your views here.

def register(request):
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}! Please Login to continue!')
            return redirect('/login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form':form})


"""
messages.debug
messages.info
messages.success
messages.warning
messages.error
"""

homepage/templates/siteRoot/addBook.html
{% extends "siteRoot/base.html" %}
{% load crispy_forms_tags %}


{%block content%}
<br><br><br>
<div id=form>
{% crispy form form.helper %}
</div>

{%endblock content%}

homepage/templates/siteRoot/base.html
<!DOCTYPE html>
<html>
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>
    <style>
    
.header{
    position: relative;
    width: 100%;
    z-index: 100;
}



ul{
    top: 0;
    position: fixed;
    font-size: 3vh; 
    list-style-type: none;
    margin-top: 0;
    margin-left: 0;
    padding: 0;
    left: 0;
    background-color: rgb(0, 135, 150);
    overflow: hidden;
    min-width: 100%;
    
}

ul li{
    min-height: 5vh;
    padding-top: 1vh;
    background-color: rgb(0, 135, 150);
    float: left;
    
}

ul li a{
    text-decoration: none;
    background-color: rgb(0, 124, 138);
}

ul li a:hover{
    color: white;
    background-color: rgb(0, 107, 119);
    
}
.loginSec a{
    color: white;
    padding:10px;
    background-color: rgb(0, 124, 138);
}
.loginSec a:hover{
    background-color: rgb(0, 107, 119);
}
.loginSec{
    color: white;
    background-color: rgb(0, 124, 138);
    text-decoration: none;
    top: 1.05vh;
    position: fixed;
    font-size: 3vh; 
    list-style-type: none;
    margin-top: 0;
    margin-left: 0;
    padding: 0;
    left: 80vw;
    overflow: hidden;
}

#afss{
    padding-left: calc(50px );
    padding-right: calc(8vw);
    font-size: 2vw;
    color: white;
    top: -50%;
    transform: translate(0%, -11%);
}
.afs{
    color: white;
    transition: all 0.5s;
    font-size: 1.25vw;
    padding-left: 1.5vw;
    padding-right: 1.5vw;
    
    text-decoration: none;
    
}

#login:hover{
    color: white;
    background-color: rgb(0, 107, 119);
    
}

body{
    margin-top: 6vh;
    margin-left: 0;
    margin-bottom: 0;
    background-color:rgb(250, 235, 215);
    
}

body #shell{
    min-width: 100vw;
    min-height: 100vh ;
    background-size: cover;
    background-attachment: fixed;
    background-color: rgb(250, 235, 215);
    color: rgb(0, 135, 150);
}

body #shell #kms{
    position: absolute;
    top: 50%;
    left: 50%;
    padding-top: 1vh;

    width: 40vw;
    height: 10vh;
    transform: translate(-50%, -195%);
    background-color: rgb(226, 214, 197);
    /*rgb(0, 135, 150)*/
    /*rgb(187, 136, 102)*/
    border-radius: 100px;
}

body #aboutPage{
    position: absolute;
    background-color: rgb(226, 214, 197);
    width: 40vw;
    padding: 2vw;
    border-radius: 100px;
    top:50%;
    left:50%;
    transform: translate(-50%, 0%);
}



body #shell #title{
    padding-left: 6.5vw;
    font-size: 3vw;
}

/*Booklist*/
body #blBg{
    /*9.5*/
    
    position:relative;
    overflow-block:initial;
    width: 100vw;
    resize: vertical;
    height: fit-content;
    background-size: cover;
    background-color: rgb(250, 235, 215);
    color: rgb(0, 135, 150);
}

body #blBg #contentResults{
    position:absolute;
    width: 100vw;
    top: 150px;
}
body #blBg #contentResults .contentBoxes{
    margin-right: 20vw;
    border-radius: 30px;
    position: relative;
    margin-left: 25vw;
    text-align: center;
    margin-top: 30px;
    padding: 10px;
    font-size: 2vw;
    background-color: rgb(226, 214, 197);
    transition: all 0.25s;
    transition-delay: 0.15s;
}
body #blBg #contentResults .contentBoxes a{
    text-decoration: none;
    color: rgb(0, 135, 150);
    transition: all 0.25s;
    transition-delay:0.25s;
}
body #blBg #contentResults .contentBoxes:hover{
    color: azure;
    background-color: coral;
    scale: 1.2;
}
body #blBg #contentResults .contentBoxes:hover > a{
    color: azure;
}

body .add_form{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -45%);
    width: 50vw;
    height: 80vh;
    background-color: rgb(0, 135, 150);
    border-radius: 100px;
    padding: 2vw;
    color: white;
    font-size: 2vw;
    text-align: center;}

#id_title{
    background-color: rgb(233, 233, 233);
    width: 40vw;
}

#id_author{background-color: rgb(233, 233, 233);
width: 40vw;}

#id_summary{background-color: rgb(233, 233, 233);
width: 40vw;}

#id_id{
    background-color: rgb(233, 233, 233);
    width: 40vw;
}
#form{
    position: absolute;
    left: 50%;
    transform: translate(-50%, 0%);
}
body #searchBox{
    position: absolute;
    top: 0%;
    left: 50%;
    transform: translate(-50%, 0%);
    width: 100%;
    height: 10vh;
    padding: 2vw;
    
    font-size: 2vw;
    text-align: center;
}
body #searchBoxInputArea{
    width: 26.25vw;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
}
body #searchBoxInputArea:focus{
    width: 80%;
}

    </style>
    <title>Library Main Menu</title>
    <div class=header>
        <ul>
            <li id=afss>Northcoast National Primary Prison</li>
            <li><a class=afs href="/">Home</a></li>
            <li><a class=afs href="/booklist">Book index</a></li>
            {%if isPartOf%}
                <li><a class=afs href="/addbook">Add a book</a></li>
            {%endif%}
            <li><a class=afs>         </a></li>
            <li><a class=afs>         </a></li>
            <li><a class=afs>         </a></li>
            <li><a class=afs>         </a></li>
            {%if user.is_authenticated%}
                <li><a class=afs href="/logout">Logout</a></li>
            {%else%}
                <li><a class=afs href="/login">Login</a></li>
                <li><a class=afs href="/register">Register</a></li>
            {%endif%}
            
            
        </ul>
        
    </div>  
</head>



    
<body>
{%if messages%}
    {%for message in messages%}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
    {%endfor%}
{%endif%}
{% block content %}{% endblock %}
</body>
</html>

homepage/templates/siteRoot/bookList.html
{% extends "siteRoot/base.html" %}

{%block content%}

<div id='blBg'>
    <div id='searchBox'><form action="{% url 'search' %}"><input id="searchBoxInputArea"type="text" name="search" placeholder="Search... Id or Title or Author"></form></div>
    <div id=contentResults>
        {% for i in box %}
            <div class=contentBoxes><a href={{i.id}}>{{i.title}}</a></div>
        {% endfor %}
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    {%for i in boxes%}
        <br><br><br><br><br><br>
    {%endfor%}
    {%if yes%}
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    {%endif%}
</div>
{%endblock content%}

homepage/templates/siteRoot/bookPage.html
{% load crispy_forms_tags %}
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="../static/siteRoot/style1.css">
</head>

<body>
<h1><a href='/booklist'>Back to index<a> <div id=title>Title: {{book_id.title}}</div><div id=id>Author: {{book_id.author}}</div></h1>
<div id=author>Book ID: {{book_id.id}}</div>


<div id=Date>
    Date Added: {{book_id.date}}
</div>
<div id=Checked>
    Checked Out: 
    {%if book_id.checked_out%}
        Yes<br/> 
            {%if isPartOf%}
                The book is checked out to: {{book_id.book_owner}}
            {%endif%}
    {%else%}
        No
    {%endif%}

</div>
{%if isPartOf%}
    <div id='Checkinout'>
    {% crispy form form.helper %}
    </div>
{%endif%}
</body>

</html>

homepage/templates/siteRoot/home.html
{% extends "siteRoot/base.html" %}

{% block content %}

<div id = shell>
    <div id = kms>
        <span id = title>Welcome to the library</span>
    </div>
    <div id=aboutPage>
    <h1>About:</h1>
    <h2>We are an organisation who has created a library management app. We aim to be:<br>  1. Easy to use<br>  2. Accesible <br>3.Visually appealing <br>
    We wish that we fullfil these goals and that you enjoy our app as it was created, 
    have fun and get reading!</h2>
    </div>
</div>

{%endblock content%}

homepage/templates/siteRoot/search.html
{% extends "siteRoot/base.html" %}

{%block content%}

<div id='blBg'>
    <div id='searchBox'><form action="{% url 'search' %}"><input id="searchBoxInputArea"type="text" name="search" placeholder="Search... Id or Title or Author"></form></div>
    <div id=contentResults>
    {% if result %}
        
        <div class=contentBoxes><a href='/booklist'>Back to full index</a></div>
        {% for i in result %}
            <div class=contentBoxes><a href='/booklist/{{i.id}}'>{{i.title}}</a></div>
        {% endfor %}
    {%endif%}
    {%if result1%}
        {% for i in result1 %}
            {%if i not in result%}
            <div class=contentBoxes><a href='/booklist/{{i.id}}'>{{i.title}}</a></div>
            {%endif%}
        {% endfor %}
    {%endif%}
    {%if not result and not result1%}
        <div class='contentBoxes'><a href='/booklist/'>No Results</a></div>
    {%endif%}
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    {%for i in result%}
        <br><br><br><br><br><br>
    {%endfor%}
    {%if yes%}
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    {%endif%}
</div>
{%endblock content%}

users/templates/users/base.html
<!DOCTYPE html>
<html>
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>
    <style>
    
.headerr{
    position: relative;
    width: 100%;
    z-index: 100;
}



#ulI{
    top: 0;
    position: fixed;
    font-size: 3vh; 
    list-style-type: none;
    margin-top: 0;
    margin-left: 0;
    padding: 0;
    left: 0;
    background-color: rgb(0, 135, 150);
    overflow: hidden;
    min-width: 100%;
    
}

#ulI li{
    min-height: 5vh;
    padding-top: 1vh;
    background-color: rgb(0, 135, 150);
    float: left;
    
}

#ulI li a{
    text-decoration: none;
    background-color: rgb(0, 124, 138);
}

#ulI li a:hover{
    color: white;
    background-color: rgb(0, 107, 119);
    
}
.loginSec a{
    color: white;
    padding:10px;
    background-color: rgb(0, 124, 138);
}
.loginSec a:hover{
    background-color: rgb(0, 107, 119);
}
.loginSec{
    color: white;
    background-color: rgb(0, 124, 138);
    text-decoration: none;
    top: 1.05vh;
    position: fixed;
    font-size: 3vh; 
    list-style-type: none;
    margin-top: 0;
    margin-left: 0;
    padding: 0;
    left: 80vw;
    overflow: hidden;
}

#afss{
    padding-left: calc(50px );
    padding-right: calc(8vw);
    font-size: 2vw;
    color: white;
    top: -50%;
    transform: translate(0%, -11%);
}
.afs{
    color: white;
    transition: all 0.5s;
    font-size: 1.25vw;
    padding-left: 1.5vw;
    padding-right: 1.5vw;
    
    text-decoration: none;
    
}

#login:hover{
    color: white;
    background-color: rgb(0, 107, 119);
    
}

body{
    margin-top: 8vh;
    margin-left: 0;
    margin-bottom: 0;
    background-color:rgb(250, 235, 215);
    
}
#registerForm{
    padding: 20px;
    margin-left:25vw;
    margin-top: 15vh;
    background-color: rgb(238, 223, 204);
    width: 50vw;
}
    </style>
    <title>Library Main Menu</title>

</head>



    
<body>
    <div class=headerr>
        <ul id=ulI>
            <li id=afss>Northcoast National Primary Prison</li>
            <li><a class=afs href="/">Home</a></li>
            <li><a class=afs href="/booklist">Book index</a></li>
            
            {%if isPartOf%}
                <li><a class=afs href="/addbook">Add a book</a></li>
            {%endif%}
            <li><a class=afs>         </a></li>
            <li><a class=afs>         </a></li>
            <li><a class=afs>         </a></li>
            <li><a class=afs>         </a></li>
            {%if user.is_authenticated%}
                <li><a class=afs href="/logout">Logout</a></li>
            {%else%}
                <li><a class=afs href="/login">Login</a></li>
                <li><a class=afs href="/register">Register</a></li>
            {%endif%}
            
        </ul>
        
    </div>  
<div class=godown>

{% block content %}{% endblock %}
</div>
</body>
</html>

users/templates/users/login.html
{%extends 'users/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
    <div id='registerForm'>
        <form method='POST'>
            {%csrf_token%}
            <fieldset class="form-group">
                <legend class='border-bottom mb-4'>Login</legend>
                {{form|crispy}}
            </fieldset>
            
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Login</button>
                <h4 class="text-muted h6">Need an account? <a href='/register'>Click here!</a></h4>
            </div>
        </form>
    </div>
{%endblock content%}

users/templates/users/logout.html
{%extends 'users/base.html'%}
{%block content%}
            <h1 class='h1'>You Have Been Logged Out</h1>
            <br/>
            <h4 class="h4">To log in again <a href='/login'>Click here!</a></h4>
{%endblock content%}

users/templates/users/register.html
{%extends 'users/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
    <div id='registerForm'>
        <form method='POST'>
            {%csrf_token%}
            <fieldset class="form-group">
                <legend class='border-bottom mb-4'>Register</legend>
                {{form|crispy}}
            </fieldset>
            
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Register</button>
                <h4 class="text-muted h6">Already Have An Account? <a href='/login'>Click here!</a></h4>
            </div>
        </form>
    </div>
{%endblock content%}